// This file automatically generated by:
//   Apache Etch 1.2.0-incubating (LOCAL-0) / java 1.2.0-incubating (LOCAL-0)
//   Fri Apr 01 10:11:34 CEST 2011
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

package DABInterface;

/**
 * Your custom implementation of BaseDABControllerClient. Add methods here to provide
 * implementations of messages from the server.
 */
public class ImplDABControllerClient extends BaseDABControllerClient
{
	/**
	 * Constructs the ImplDABControllerClient.
	 *
	 * @param server a connection to the server session. Use this to send a
	 * message to the server.
	 */
	public ImplDABControllerClient( RemoteDABControllerServer server )
	{
		this.server = server;
	}
	
	/**
	 * A connection to the server session. Use this to send a
	 * message to the server.
	 */
	@SuppressWarnings( "unused" )
	private final RemoteDABControllerServer server;
	
	// TODO insert methods here to provide implementations of DABControllerClient
	// messages from the server.
}
